# Generated by Django 3.2.15 on 2023-05-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    def update_price(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        order_items = OrderItem.objects.all()
        for item in order_items:
            if item.price is None:
                item.price = item.product.price
                item.save()

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(update_price),
    ]
