# Generated by Django 3.2.15 on 2023-06-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230601_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Cash', 'Наличностью'), ('E-money', 'Электронно'), ('No choice', 'Не выбрано')], db_index=True, default='No choice', max_length=9, verbose_name='Способ оплаты'),
        ),
    ]
