# Generated by Django 3.2.15 on 2023-06-07 05:17

from django.db import migrations


def change_comment(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        if order.comment is None:
            order.comment = ''
            order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230601_1120'),
    ]

    operations = [
        migrations.RunPython(change_comment),
    ]
